apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyeduzalo
  namespace: production
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: easyeduzalo
  template:
    metadata:
      labels:
        app: easyeduzalo
    spec:
      containers:
        - name: easyeduzalo
          image: harbor.emso.vn/emso-common/zaloeasyedu:0.0.2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: easyeduzalo-config
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: easyeduzalo-uploads-pvc
      imagePullSecrets:
        - name: emso-harbo-production
