apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - hpa.yaml
  - configmap.yaml
  - pvc.yaml
labels:
  - includeSelectors: true
    pairs:
      app: easyeduzalo
      release: production
