apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easyeduzalo-uploads-pvc
  namespace: production

spec:
  storageClassName: highio-az4

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 20Gi